### ISSUE TITLE
请问下您自定义抠图接口是用了哪个开源模型吗？

### ISSUE THREAD

**Issue by bookmarkbao** [KID-1912/fabric-remove-bg#1]
[/api/ai/v1/koutu](https://design.palxp.cn:5175/api/ai/v1/koutu)
/api/ai/v1/koutu 这个接口，您是自己实现，用了哪家的接口吗？还是自己部署实现的抠图呀

**Comment by KID-1912** [comment]
该接口来自于另一个开源低代码项目：https://github.com/palxiao/poster-design 的抠图功能，你可以去那里留言
